AllCops:
  NewCops: enable
  Exclude:
    - 'Guardfile'
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Layout/EmptyLinesAroundArguments:
  Exclude:
    - 'spec/**/*'