AllCops:
  NewCops: enable
  Exclude:
    - 'Guardfile'
    - 'spec/spec_helper.rb'

Metrics/ClassLength:
  CountAsOne: [array, hash]

Metrics/MethodLength:
  Max: 20
  IgnoredMethods: [puts]
  CountAsOne: [array, hash]

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Layout/EmptyLinesAroundArguments:
  Exclude:
    - 'spec/**/*'